name: Medium Writeups

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Scrape Medium Writeups
        run: |
          go run main.go | tee NEW-README.md

      - name: Replace old README.md with new version
        run: |
          mv NEW-README.md README.md

      - name: Commit and push changes if there are any
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md

          # Check if there are changes before committing
          if ! git diff --cached --quiet; then
            IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
            git commit -m "Updated List: $IST_DATE"
            git push
          else
            echo "No changes to commit"
          fi
